# Destination objects (created automatically if missing)
quarantine_table: dq.quarantine # catalog.schema.table or schema.table
metrics_table: dq.metrics


# Dashboard views (created automatically)
views:
rule_results: dq.v_dq_rule_results
table_health: dq.v_dq_table_health
column_nulls: dq.v_dq_column_nulls


# Execution mode: batch | streaming
mode: batch


# Incremental options (batch mode)
incremental:
use_cdf: false # if true, read only CDF changes (requires table property)
starting_version: 0


# Auto Loader (used if mode=streaming)
streaming:
input_format: json # json | csv | parquet | avro | etc
input_path: /mnt/raw/users
schema_location: /mnt/_schemas/users
checkpoint: /mnt/_chk/users
output_table: silver.users # where passing rows land
trigger: processingTime=1 minute # use availableNow for catch-up once


# Scope of targets to validate: table | schema | catalog
scope: schema
catalog: hive_metastore
schema: sales
# When scope=schema or catalog, select which tables
include: ["*"] # glob patterns
exclude: ["_dq_*", "tmp*"]


# Default rules for all targets (override per-table below)
rules:
- type: not_null
name: nn_id
cols: [id]
- type: range
name: amt_non_negative
col: amount
min: 0
- type: check
name: email_ok
expr: email RLIKE '^[^@]+@[^@]+\\.[^@]+$'


# Per-table overrides (optional)
tables:
hive_metastore.sales.orders:
rules:
- type: not_null
name: nn_order
cols: [order_id, customer_id]
- type: uniqueness
name: uq_order
cols: [order_id]


# Custom rules module path (optional). If present, will be imported and registered.
custom_rules_module: custom_rules
